# Generated by Django 4.0.4 on 2022-05-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comingsoon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comingsoonnotice',
            name='referral',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comingsoon.comingsoonnotice'),
        ),
        migrations.AlterField(
            model_name='comingsoonnotice',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
